#!/usr/bin/env bash
# ci-walden tenant-interface v1 — generated by ci-walden tenant-init
# stack: rust-docker (Cargo.toml; runner image has no native cargo — test via rust:1)
# contract: bash at repo root; exit status is the verdict (0 = green)
# regenerating this file on an unchanged repo is a no-op diff
set -e
docker run --rm -v "$PWD":/w -w /w rust:1 cargo test
